=== th2-net/th2-codec-xml/sample-resourses/examples/music_band.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- targetNamespace="http://xml.netbeans.org/schema/newXmlSchema"-->
<xs:schema elementFormDefault="qualified"
           xmlns="urn:Test.Namespace"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://anything.com"
           xmlns:pref="http://22222">

    <xs:import schemaLocation="registration.xsd" namespace="http://22222"/>

    <xs:element name="instruments">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pref:fields"/>
                <xs:element name="guitar">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="strings">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="string" type="xs:int" minOccurs="6" maxOccurs="8"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="vocal">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sex" type="xs:string"/>
                            <xs:element name="voice" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="drumkit">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cymbals">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="component" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="drums">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="component" type="xs:string" minOccurs="2" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="bass">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="strings" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== th2-net/th2-codec-xml/sample-resourses/examples/default-band.xml
<?xml version="1.0" encoding="UTF-8"?>
<n1:instruments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://anything.com music_band.xsd http://22222 registration.xsd"
             xmlns:n1="http://anything.com"

             >

    <n2:fields xmlns:n2="http://22222">
        <n2:FirstName>Alexandr</n2:FirstName>
        <n2:LastName>Potagashev</n2:LastName>
        <n2:DateOfBirth>06.04.2002</n2:DateOfBirth>
        <n2:PhoneNumber>89234170028</n2:PhoneNumber>
    </n2:fields>

    <n1:guitar>
        <n1:type>electric</n1:type>
        <n1:strings>
            <n1:string>1</n1:string>
            <n1:string>2</n1:string>
            <n1:string>3</n1:string>
            <n1:string>4</n1:string>
            <n1:string>5</n1:string>
            <n1:string>6</n1:string>
        </n1:strings>
    </n1:guitar>
    <n1:vocal>
        <n1:sex>male</n1:sex>
        <n1:voice>tenor</n1:voice>
    </n1:vocal>

    <n1:drumkit>
        <n1:cymbals>
            <n1:component>crash</n1:component>
            <n1:component>hat</n1:component>
            <n1:component>ride</n1:component>
        </n1:cymbals>
        <n1:drums>
            <n1:component>snare</n1:component>
            <n1:component>tom-tom</n1:component>
            <n1:component>bass</n1:component>
        </n1:drums>
    </n1:drumkit>

    <n1:bass>
        <n1:strings>4</n1:strings>
    </n1:bass>

</n1:instruments>
